# Install script for directory: C:/dev/fltk-1.3.2/test

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Archivos de programa/FLTK")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/adjuster.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/adjuster.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/adjuster.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/adjuster.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/adjuster.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/arc.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/arc.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/arc.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/arc.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/arc.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/ask.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/ask.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/ask.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/ask.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/ask.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/bitmap.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/bitmap.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/bitmap.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/bitmap.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/bitmap.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/blocks.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/blocks.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/blocks.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/blocks.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/blocks.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/boxtype.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/boxtype.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/boxtype.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/boxtype.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/boxtype.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/browser.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/browser.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/browser.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/browser.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/browser.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/button.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/button.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/button.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/button.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/button.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/buttons.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/buttons.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/buttons.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/buttons.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/buttons.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/checkers.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/checkers.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/checkers.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/checkers.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/checkers.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/clock.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/clock.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/clock.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/clock.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/clock.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/colbrowser.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/colbrowser.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/colbrowser.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/colbrowser.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/colbrowser.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/color_chooser.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/color_chooser.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/color_chooser.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/color_chooser.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/color_chooser.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/cursor.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/cursor.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/cursor.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/cursor.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/cursor.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/curve.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/curve.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/curve.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/curve.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/curve.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/demo.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/demo.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/demo.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/demo.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/demo.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/device.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/device.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/device.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/device.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/device.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/doublebuffer.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/doublebuffer.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/doublebuffer.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/doublebuffer.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/doublebuffer.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/editor.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/editor.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/editor.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/editor.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/editor.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fast_slow.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/fast_slow.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fast_slow.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fast_slow.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fast_slow.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/file_chooser.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/file_chooser.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/file_chooser.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/file_chooser.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/file_chooser.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fonts.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/fonts.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fonts.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fonts.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fonts.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/forms.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/forms.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/forms.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/forms.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/forms.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/hello.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/hello.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/hello.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/hello.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/hello.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/help.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/help.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/help.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/help.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/help.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/iconize.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/iconize.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/iconize.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/iconize.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/iconize.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/image.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/image.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/image.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/image.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/image.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/inactive.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/inactive.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/inactive.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/inactive.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/inactive.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/input.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/input.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/input.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/input.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/input.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/input_choice.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/input_choice.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/input_choice.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/input_choice.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/input_choice.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/keyboard.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/keyboard.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/keyboard.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/keyboard.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/keyboard.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/label.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/label.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/label.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/label.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/label.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/line_style.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/line_style.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/line_style.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/line_style.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/line_style.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/list_visuals.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/list_visuals.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/list_visuals.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/list_visuals.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/list_visuals.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/mandelbrot.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/mandelbrot.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/mandelbrot.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/mandelbrot.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/mandelbrot.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/menubar.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/menubar.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/menubar.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/menubar.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/menubar.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/message.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/message.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/message.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/message.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/message.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/minimum.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/minimum.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/minimum.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/minimum.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/minimum.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/native-filechooser.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/native-filechooser.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/native-filechooser.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/native-filechooser.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/native-filechooser.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/navigation.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/navigation.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/navigation.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/navigation.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/navigation.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/output.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/output.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/output.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/output.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/output.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/overlay.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/overlay.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/overlay.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/overlay.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/overlay.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/pack.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/pack.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/pack.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/pack.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/pack.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/pixmap.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/pixmap.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/pixmap.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/pixmap.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/pixmap.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/pixmap_browser.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/pixmap_browser.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/pixmap_browser.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/pixmap_browser.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/pixmap_browser.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/preferences.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/preferences.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/preferences.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/preferences.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/preferences.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/radio.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/radio.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/radio.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/radio.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/radio.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/resize.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/resize.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/resize.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/resize.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/resize.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/resizebox.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/resizebox.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/resizebox.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/resizebox.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/resizebox.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/rotated_text.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/rotated_text.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/rotated_text.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/rotated_text.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/rotated_text.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/scroll.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/scroll.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/scroll.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/scroll.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/scroll.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/subwindow.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/subwindow.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/subwindow.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/subwindow.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/subwindow.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/sudoku.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/sudoku.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/sudoku.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/sudoku.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/sudoku.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/symbols.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/symbols.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/symbols.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/symbols.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/symbols.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tabs.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/tabs.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tabs.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tabs.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tabs.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/table.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/table.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/table.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/table.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/table.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/threads.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/threads.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/threads.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/threads.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/threads.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tile.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/tile.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tile.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tile.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tile.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tiled_image.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/tiled_image.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tiled_image.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tiled_image.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tiled_image.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tree.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/tree.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tree.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tree.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/tree.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/utf8.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/utf8.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/utf8.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/utf8.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/utf8.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/valuators.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/valuators.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/valuators.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/valuators.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/valuators.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/unittests.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/unittests.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/unittests.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/unittests.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/unittests.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/CubeView.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/CubeView.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/CubeView.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/CubeView.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/CubeView.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/cube.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/cube.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/cube.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/cube.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/cube.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fractals.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/fractals.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fractals.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fractals.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fractals.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fullscreen.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/fullscreen.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fullscreen.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fullscreen.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/fullscreen.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/glpuzzle.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/glpuzzle.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/glpuzzle.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/glpuzzle.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/glpuzzle.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/gl_overlay.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/gl_overlay.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/gl_overlay.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/gl_overlay.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/gl_overlay.exe")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "C:/Archivos de programa/FLTK/share/doc/FLTK/examples/shape.exe")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "C:/Archivos de programa/FLTK/share/doc/FLTK/examples" TYPE EXECUTABLE FILES "C:/dev/fltk-1.3.2/bin/examples/shape.exe")
  if(EXISTS "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/shape.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/shape.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "C:/MinGW/bin/strip.exe" "$ENV{DESTDIR}/C:/Archivos de programa/FLTK/share/doc/FLTK/examples/shape.exe")
    endif()
  endif()
endif()

